	<a href="https://www.facebook.com/dialog/feed?app_id=<?php print FACEBOOK_APP_ID; ?>&display=popup&caption=<?php print urlEncode($facebookMessage); ?>&link=https://4and.me/<?php print $projectId; ?>" target="_blank"> 
  		<img src="https://simplesharebuttons.com/images/somacro/facebook.png"
  			alt="Facebook" align="middle" height="60" width="60" />
  	</a>
    &nbsp;&nbsp;&nbsp;
    <a href="https://twitter.com/share?url=https://4and.me/<?php print $projectId; ?>;text=<?php print urlencode($twitterMessage); ?>&amp;hashtags=villagex"
		    target="_blank"> <img
		    src="https://simplesharebuttons.com/images/somacro/twitter.png"
		    alt="Twitter" align="middle" height="60" width="60" />
   </a>
