<?php include('header.inc'); ?>

<div class="container">
	<h3 style="text-align:center">Terms of Service</h3>
		<p>These terms of service govern the relationship between Friends of Village X Inc (dba Village X Org) and anyone who uses or has access to, or attempts to use or gain access to, any application provided by Village X Org.  The terms and conditions set forth herein apply regardless of the environment in which the application is used, the geographic location of such use and the technical means employed therefore. Please consider the below text carefully for it is only if you fully agree with all terms and conditions contained herein that you may use the application referred to. If you find anything in this document that you do not understand or agree with, please refrain from using Village X's application. Any use or access of the same or any attempt to do so shall be deemed to constitute your consent to be bound by these terms of service.</p>
					<h6><b>1. Interpretation</b></h6>
						<p>1.1. The following terms, when capitalized, shall have the meanings assigned to them below:</p>
						<p>"Agreement" -- these terms of service (as amended from time to time), Village X's privacy policy (available at www.villagex.org) and such other terms concerning Village X's application as Customer may agree to via the Service when prompted to by Village X;</p>
						<p>"Content" -- the information (including text, images, audio and video material), functionality and technical resources provided by Supplier as a part of, through or in conjunction with the Software.</p>
						<p>"Customer" -- any person or entity that has a valid User Account. Each Customer should take this term as referring specifically to them, unless the context otherwise requires;</p>
						<p>"Customer Details" -- all Personal Data about Customer that Customer provides to Supplier in connection with this Agreement or the Service. Customer Details may, for example, include such information as Customer's name, address, email address, picture, time zone, tax registration number and information about which third-party services Customer uses for accessing or otherwise in conjunction with the Service;</p>
						<p>"Intellectual Property" -- all existing and future trademarks, service marks, domain names and business names, rights pertaining to inventions, designs, databases and proprietary information (including, without limitation, trade secrets and know-how), patents, copyrights, moral rights and all other assets and benefits commonly regarded as intellectual property, whether registered or not;</p>
						<p>"Party" -- each of Customer and Supplier;</p>
						<p>"Personal Data" -- any information about a natural person that comes under the legal definition of "personal data" as provided under applicable law (At the time these terms of service were last revised, the legal definition of personal data read as follows: any data relating to an identified or identifiable natural person, regardless of the form or format in which such data exist);</p>
						<p>"Service" -- depending on the context, either (i) Supplier's making available of the Software, Content and customer support (all of which are made available "as a service"), or (ii) Software, Content and customer support collectively or in any combination;</p>
						<p>"Significant Change" -- any change to the terms of this Agreement that reduces Customer's rights or increases Customer's responsibilities;</p>
						<p>"Software" -- Village X software for project perusal, selection, giving (directly or via a campaign), and impact reporting, and such other Supplier-developed software applications as Supplier may make available in conjunction therewith, including such modifications and replacements thereof as Supplier may from time to time provide;</p>
						<p>"Supplier" -- Village X Org, a nonprofit social enterprise based in Washington, DC. for inquires, send an email to info@villagex.org;</p>
						<p>"Third-party User" -- any person that Customer permits or causes to have access to the Service, except another Customer;</p>
						<p>"User Account" -- a Supplier-hosted or -administered account provided to Customer through the Service for the purpose of enabling Customer to use the Service;</p>
						<p>"Workspace" -- any part of the user environment provided via the Service, except Customer's personal profile page, where two or more users can interact, as opposed to merely view information. Certain Workspaces may but need not be shared with other users of the Service (depending on future features provided by Supplier, Customer and other users of the Service may decide to share or not share certain Workspaces with each other, enable and restrict each other's use of shared Workspaces as well as limit, broaden, prevent and restore access thereto);</p>
						<p>"Workspace Data" -- any information that Customer, any Third-party User or any other user of the Software, Content or any other part of the Service possesses or enters, records, stores, modifies, discloses, makes available, transmits, uses, deletes or otherwise processes in, through or by means of any Workspace.</p>
						<p>1.2. "Herein", "hereto", "hereof", "hereunder" and similar expressions, wherever used in this Agreement, shall be deemed to refer to the Agreement.</p>
						<p>1.3. This Agreement (as amended from time to time) constitutes the entire agreement between the Parties relating to the subject matter hereof and supersedes and replaces all prior agreements and understandings between the Parties with respect to that subject matter.</p>
						<p>1.4. In case of conflict or ambiguity between any provision contained herein and any statement, representation or other information published on www.villagex.org, the provision in the Agreement shall prevail.</p>
					<h6><b>2. Term</b></h6>
						<p>2.1. This Agreement shall be effective between the Parties as of the moment when Customer obtains a User Account or agrees or is deemed to have agreed to the terms hereof, whichever occurs first. The Agreement is entered into for an indefinite term and may be cancelled by either Party as provided herein.</p>
						<p>2.2. Anyone who visits the www.villagex.org website or uses, accesses or attempts to access any part of the Service shall by so doing be deemed to have agreed to the terms hereof.</p>
					<h6><b>3. Licence</b></h6>
						<p>3.1. Subject to the terms set forth herein, Supplier grants to Customer and the latter accepts a limited, non-exclusive and non-transferable license to use the Software and the Content provided on www.villagex.org.</p>
						<p>3.2. Software and Content may only be used in such manner as necessary for utilizing the Service for its intended purpose and only during the time the Agreement remains in force between the Parties.</p>
						<p>3.3. The Service may only be accessed through the interface(s) Supplier has provided therefore and shall not be accessed or attempted to be accessed in any manner not approved by Supplier.</p>
						<p>3.4. With respect to assignment, sub-licensing and other disposals, the Parties have agreed that: (i) Customer shall not, without the prior explicit consent of Supplier, sub-license, assign, encumber or otherwise dispose of any right, benefit or obligation hereunder, except that Customer may assign and encumber their monetary claims without requiring Supplier's consent; (ii) Supplier may: (a) in its sole discretion sub-license, assign, encumber and otherwise dispose of any and all of its rights and benefits hereunder; (b) dispose in any manner of any and all of its obligations under this Agreement, provided it notifies Customer thereof.</p>
						<p>3.5. No license or other right with respect to the Software, Content or any other part of the Service is granted by this Agreement to anyone other than the Parties.</p>
					<h6><b>4. Service</b></h6>
						<p>4.1. Supplier will use commercially reasonable efforts to provide the Service to Customer throughout the term of this Agreement.</p>
						<p>4.2. Customer acknowledges that: (i) the Service has not been designed to meet Customer's individual requirements; (ii) the operation of the Service may from time to time encounter technical or other problems and may not continue uninterrupted or without errors; (iii) the Service is not fault-tolerant and has not been designed for use in inherently dangerous circumstances, such as, e.g., the operation of "major sources of danger", traffic control or life support systems, handling hazardous substances and other activities where the failure of the Service could lead to death, personal injury or environmental damage.</p>
						<p>4.3. The Service (including all Software and Content) is provided on an "as is" and "as available" basis. Customer's selection and use of the Service is at Customer's own risk, and so are Customer's and Third-party Users' exposure to, down- and upload of, as well as transmission, other processing and possession of information, programs and other objects through or due to the Service.</p>
						<p>4.4. Supplier has no obligation to enhance, modify or replace any part of the Service or to continue developing or releasing new versions thereof.</p>
						<p>4.5. Technical support is provided via the Service feedback feature (info@villagex.org) and only in English. Supplier aims to answer most support issues within 24 business hours but is under no obligation to do so and makes no guarantee on how quickly support is provided or issues will be resolved.</p>
						<p>4.6. Some parts of the Service may have been translated into other languages, but it is only those that are available in English that Supplier has approved for use.</p>
						<p>4.7. The Service may provide links or access to third-party websites, resources or services and these may provide links or access to the Service. Supplier is not responsible for the qualities (including the availability, reliability and security) of such external sites, resources or services, does not endorse them and shall not be liable for any loss, damage, expenses or other consequences resulting from their existence, qualities, use or inability to use them.</p>
					<h6><b>5. Payment</b></h6>
						<p>5.1. By donating to a project, Customer shall be deemed to have agreed to and accepted liability for the payment of all fees, rates and other charges associated with that action. The same applies in a situation where Customer permits or causes oneself to be designated as the payer for someone else's donation.</p>
						<p>5.2. All donations for the Service are handled by a third-party payment gateway (currently, Stripe). Supplier is not responsible for the processing of Customer's donations and shall not be liable for any matter in connection therewith. Supplier does not maintain confidential customer payment information (e.g., credit card numbers).</p>
						<p>5.3. All donations are exclusive of value added tax, sales tax and other public burdens, if applicable. Customer shall be solely responsible for all taxes and burdens that may be levied on their donation.</p>
					<h6><b>6. Customer undertaking</b></h6>
						<p>6.1. Customer must be a person (either natural or legal) or an entity with legal capacity.</p>
						<p>6.2. Supplier's policy is not to solicit or otherwise induce or influence any person not possessing active legal capacity (including persons whose active legal capacity has been restricted or is deemed to be restricted) to subscribe to the Service or to use the same. For the protection of those whose active legal capacity is restricted, Supplier prohibits any such person from subscribing to, being subscribed to, and from using, the Service. In case of natural persons, full active legal capacity is usually acquired by becoming of legal age, which, pursuant to the law applicable to this Agreement, occurs when one attains 18 years of age. It is for the aforesaid reasons that the natural-person Customer and any representative of a non-natural-person Customer must represent to Supplier, and by his/her subscribing to the Service (or, respectively, by subscribing Customer to the Service) does so represent, that s/he is at least 18 years of age and fully capable of entering into binding contracts. The same representation is deemed to be made each time the Service is used and Customer acknowledges that Supplier relies on this representation being true throughout the term of the Agreement.</p>
						<p>6.3. Customer acknowledges that Supplier is not obliged to verify Customer Details and may rely on these details without verification.</p>
						<p>6.4. Customer must comply and shall cause Third-party Users to comply with all laws, rules and regulations applicable to their use of the Service and their acquisition, possession and processing of Workspace Data.</p>
						<p>6.5. With respect to the information (including all text, images, audio-visual material, Personal Data and other content) that Customer or any Third-party User acquires, possesses or enters, records, stores, modifies, discloses, makes available, transmits, uses, deletes or otherwise processes via the Service, Customer represents and warrants to Supplier that Customer or, respectively, the relevant Third-party User, has the right to acquire, possess and process the same. Customer shall be solely responsible for the properties of the said information and the acquisition, possession and processing of such information under, through or by means of Customer's User Account.</p>
						<p>6.6. Customer shall not, and shall cause Third-party Users not to, use the Service for sending unsolicited communications or for uploading, transmitting, delivering, running, possessing or storing harmful code, malware or illegal content.</p>
						<p>6.7. Any Customer content that conflicts with the provisions of this Agreement may be removed, disabled and/or destroyed by Supplier at its sole discretion without any warning or notice.</p>
						<p>6.8. Without excluding or limiting any of Customer's statutory obligations, Customer undertakes to Supplier that Customer will not, and will not allow any Third-party User to: (i) use any device, software or routine to interfere or attempt to interfere with the proper functioning of the Service; (ii) impose an unreasonable or disproportionately heavy load on the Service or its infrastructure; (iii) copy, modify, reproduce or create derivative works from, or decompile, reverse engineer or otherwise attempt to derive source code from the Software or any other part of the Service; (iv) remove, alter, hide or obscure any copyright notice, trademark or other proprietary rights notice embedded in, appearing on or otherwise pertaining to the Service; or (v) create or attempt to create any product or service that is substantially similar to or otherwise competes with the Service or purports to be created, provided or approved by Supplier.</p>
						<p>The undertakings of Customer set forth in this section 6.8 shall also be deemed to have been made by anyone who visits the www.villagex.org website or uses, accesses or attempts to access any part of the Service.</p>
					<h6><b>7. Representative's Undertaking</b></h6>
						<p>7.1. Any person that subscribes Customer to the Service or otherwise represents Customer upon the latter's entry into the Agreement shall by so doing be deemed to have personally represented and undertaken to Supplier that s/he has the authority to act on Customer's behalf and that the Agreement is binding on Customer. Each such representative hereby further undertakes to Supplier, and the latter agrees, that if this Agreement proves to be void due to the representative's lack or excess of authority or if it emerges that the representative has concluded this Agreement on behalf of a non-existent Customer then such representative shall be deemed to have entered into the Agreement on their own behalf and the Agreement shall be effective (ab initio) between Supplier and the aforesaid representative.</p>
					<h6><b>8. User Account</b></h6>
						<p>8.1. Customer shall be fully responsible for the activity that occurs under their User Account, including all acts performed through or by means of such User Account, and must notify Supplier immediately of any breach of security relating to or unauthorized use of their User Account.</p>
						<p>8.2. With respect to Customer's usernames, passwords and authentication tokens, the Parties have agreed that Customer shall be responsible for: (i) maintaining the confidentiality of their usernames, passwords and tokens; (ii) all acts performed by the use of and all consequences of use or misuse of any such username, password or token.</p>
						<p>8.3. Supplier shall not be responsible for any loss, damage or other consequences that may result from any unauthorized use of Customer's User Account, username, password or authentication token.</p>
					<h6><b>9. Intellectual Property and Proprietary Rights</b></h6>
						<p>9.1. All Service-related Intellectual Property belongs and shall belong to Supplier. Customer shall not acquire any right thereto or interest therein or otherwise in connection with the Service, except for the limited rights of use expressly set forth in this Agreement. All rights not expressly granted herein shall be deemed withheld.</p>
						<p>9.2. Neither the fact of concluding this Agreement, nor any provision contained herein, nor any breach by any Party of its obligations hereunder, shall be construed as creating in Customer or cause the latter to acquire any proprietary right, security interest, pawn or any other right of security with respect to any item or asset belonging to Supplier.</p>
						<p>9.3. Supplier may, in its sole discretion, disable, close or restrict access to any User Account that is used to infringe on anyone's Intellectual Property or proprietary or personal rights.</p>
					<h6><b>10. Contributions to the Service</b></h6>
						<p>10.1. With respect to any object of Intellectual Property or any other result of intellectual activity that is submitted, contributed or otherwise made available for inclusion in the Software, Content or any other part of the Service, Supplier shall be deemed to have been granted a non-exclusive, royalty-free, worldwide, perpetual, irrevocable and fully sub-licensable license to use, distribute, reproduce, modify, adapt, publish, translate, transmit, publicly perform, display and make available the same (in whole or in part) and to incorporate it into other works in any format or medium now known or later developed. Any person making such a contribution warrants to Supplier that they have the right to do so and agrees that they will not be entitled to any compensation or reimbursement therefore.</p>
					<h6><b>11. Disclaimer of Warranties</b></h6>
						<p>11.1. All conditions, representations and warranties not expressly stated herein (including, without limitation, those relating to merchantability, fitness for a particular purpose, non-infringement and up-time as well as those that may arise from a course of performance, course of dealing or usage of trade) shall be deemed withheld by Supplier to the fullest extent permitted by law.</p>
						<p>11.2. Supplier makes no representation or warranty (i) that the Service will meet Customer's or Third-party Users' requirements or expectations, (ii) that access to or use of the Service will be uninterrupted, timely, secure or error-free, (iii) that any defects in the Service will be corrected, (iv) that the Service or any means by which the Service is accessed or used is free of malware or other harmful components; or (v) with respect to any third-party software, content, material, information, infrastructure or other third-party resources or services that Customer or any Third-party User may acquire, use, access or be exposed to through or due to the Service.</p>
						<p>11.3. Each Party acknowledges that the other Party has entered into the Agreement relying on the above disclaimers and that these disclaimers are an essential basis of the bargain between the Parties.</p>
					<h6><b>12. Limitation of Liability</b></h6>
						<p>12.1. Supplier shall not be liable for any loss, damage, expenses or other consequences resulting from (i) anyone's use or inability to use the Service, (ii) the properties of the Service, (iii) the need to procure or the procurement of substitute goods or services or any other substitute benefit for the Service or for any information, service or other benefit received, owned, possessed or otherwise enjoyed through the Service, (iv) any message or other communication received or transaction entered into through or from the Service, (v) unauthorized access to or interruption, alteration, loss or deletion of Customer's or any Third-party User's transmissions or data, (vi) the statements or conduct of any person having access to the Service, (vii) any other matter relating to the Service; REGARDLESS of whether the same are suffered directly or indirectly or are immediate or consequential, and whether the same arise in contract, tort or otherwise; PROVIDED, HOWEVER, that (a) this section shall not prevent claims for the compensation of direct financial (patrimonial) loss suffered by Customer due to Supplier's intentional or grossly negligent breach of this Agreement or financial (patrimonial) loss resulting from Supplier's causing personal injury to, or the death of, Customer, AND that (b) the total liability of Supplier, whether in contract, tort or otherwise, shall in no circumstances exceed the amount that Customer has paid to Supplier for the Service during the twelve months immediately preceding that month in which the event giving rise to Supplier's liability occurred.</p>
						<p>12.2. No Party shall be liable to the other for breaching its obligations due to a circumstance it reasonably could not have foreseen and that is beyond its control, such as, for example, an "act of God", act of government, war, civil unrest, act of terror, strike, Internet service provider failure or any other circumstance qualifying as force majeure -- to the extent that the respective circumstance prevented or hindered the Party's performance.</p>
					<h6><b>13. Indemnification</b></h6>
						<p>13.1. Customer shall defend or settle, with no harm, cost or burden to Supplier, any lawsuit or other proceeding that is brought against Supplier based on or otherwise arising out of Customer's or any Third-party User's (i) use of the Service (including the acquisition, possession or processing of information through the Service), (ii) contribution to the Service, (iii) use, misuse or other processing of Personal Data, or (iv) infringement of Intellectual Property or any proprietary or personal right. Customer further agrees that upon Supplier's request Customer will reimburse Supplier for all reasonable costs (including reasonable attorneys' fees) that Supplier incurs in connection with any such lawsuit or proceeding.</p>
					<h6><b>14. Data Processing</b></h6>
						<p>14.1. Customer acknowledges that Customer Details and certain other information about Customer and Third-party Users is collected and processed through the Service. Supplier's use of this information is subject to its privacy policy (available at www.villagex.org). Customer understands that by using or otherwise accessing the Service Customer is deemed to have agreed to the collection and use of this information (as set forth in the privacy policy), including the transfer of this information to the country of Supplier's domicile and/or other countries for processing by Supplier and/or its contractors.</p>
						<p>14.2. Supplier shall not be considered a controller or processor (neither chief, responsible, authorized nor any other processor) of Workspace Data and has no obligation whatsoever in connection with any Workspace Data or the processing thereof. All Workspace Data shall be deemed to be processed by Customers and any inquiry, request, objection, complaint or claim that a Customer may have in connection with Workspace Data or any processing thereof should be addressed to their respective peers. Supplier is under no obligation to participate or take any action in such matters.</p>
					<h6><b>15. Modification and Suspension</b></h6>
						<p>15.1. Customer acknowledges that, from time to time, circumstances may arise that in Supplier's judgment make it necessary or desirable to modify certain provisions of this Agreement. Such circumstances may include, but are not limited to, the following: (i) the launch of a new service or a modification to the Service; (ii) a change in Supplier's policy or in its legal or business environment; (iii) the entry of a judgment or an order against or in favor of Supplier; (iv) a significant corporate event, such as, e.g., Supplier's merger or acquisition or its reorganization into a different type of entity; (v) the ambiguity, inconsistency, nullity, voidability or unenforceability of a provision herein or its becoming out of date.</p>
						<p>15.2. Customer agrees that: (i) upon the occurrence of any of the circumstances referred to above, Supplier shall be entitled to make such changes to the Agreement as it reasonably deems appropriate; (ii) Supplier's ability to foresee a particular event or to prevent it from happening shall not affect its right to amend the Agreement due to the occurrence of that event; (iii) Supplier may amend the Agreement by posting a revised version on www.villagex.org and the revised version will take effect as of the time it is posted, unless otherwise stipulated herein; (iv) if the revised version of the Agreement includes a Significant Change, Supplier will provide Customer reasonable prior notice of such new version's entry into force by sending an email to the address Customer has associated with their User Account or by posting a prominent notice on the Service.</p>
						<p>15.3. Notwithstanding anything herein to the contrary, Supplier reserves the right to modify the Service at any time for any reason, with or without notice. Unless explicitly stated otherwise, the use of any new features, versions, releases, updates or other modifications that Supplier may make available in connection with the Service shall be subject to the Agreement. Customer's continued use of the Service after any such modification(s) shall constitute Customer's consent to the respective modification(s).</p>
						<p>15.4. If Customer does not agree with the changes, or any particular change, that Supplier has made to the Agreement or the Service, Customer's sole and exclusive remedy shall be to cancel the Agreement and terminate their use of the Service.</p>
						<p>15.5. Supplier may discontinue providing the Service or any part thereof upon a month's notice and may, without notice, suspend or restrict access to the Service for any Customer whose payment for the Service remains overdue for more than a week or whose use of the Service conflicts with the provisions of this Agreement.</p>
						<p>15.6. Supplier may suspend performance under the Agreement in whole or in part with immediate effect if it is required by law or by a competent court, tribunal or regulatory body to temporarily or permanently refrain from continuing to perform its obligations hereunder.</p>
					<h6><b>16. Termination</b></h6>
						<p>16.1. The Agreement between Supplier and Customer can be terminated only by closing Customer's User Account. In order to close one's User Account, Customer must log on to the Service and activate the option in the settings or, in the absence of that option, email an account closure request to info@villagex.org.</p>
						<p>16.2. Either Party may cancel the Agreement at any time -- Customer with or without notice and Supplier upon a month's notice ("ordinary" cancellation).</p>
						<p>16.3. Upon a Party's material breach of its obligations hereunder, the other Party may cancel the Agreement forthwith, i.e. without warning or advance notice ("extraordinary" cancellation). A material breach shall, inter alia, be deemed to have occurred if: (i) a Party is in breach of any of its obligations hereunder and fails to discontinue or remedy such breach within two weeks after notice from the other Party specifying the breach and requiring it to be discontinued or remedied; (ii) a Party is in persistent breach of any of its obligations hereunder and the respective breach cannot be remedied; (iii) a breach by one Party deprives the other of the whole benefit, or substantially all of the benefit, the latter was entitled to hereunder. Other provisions of this Agreement and those of applicable law may provide additional grounds for extraordinary cancellation.</p>
						<p>16.4. Any termination of the Agreement shall be without prejudice to the Parties' rights and remedies that have accrued prior to the termination.</p>
						<p>16.5. Customer understands and agrees that upon any termination of this Agreement: (i) all rights that Customer has been granted hereunder will terminate; (ii) Customer shall cease all activities authorized by the Agreement; (iii) they shall immediately disburse to Supplier all sums that are due to the latter hereunder; (iv) all Customer content and other data associated with Customer's User Account will be deleted or otherwise made unavailable to Customer; (v) they will receive no refund, exchange or other compensation for any unused time on a subscription, for any license or subscription fee, any content or other data associated with their account, or for anything else.</p>
					<h6><b>17. Choice of Law and Jurisdiction</b></h6>
						<p>17.1. This Agreement and all matters relating to the Service shall be governed by the law of the District of Columbia.</p>
						<p>17.2. Any dispute that may arise in connection with this Agreement, whether with respect to its existence, validity, interpretation, performance, breach, termination or otherwise, and any dispute concerning the Service or any part thereof, shall, if not settled by negotiation, be subject to the exclusive jurisdiction of District of Columbia courts. Each Party and anyone who visits the www.villagex.org website or uses, accesses or attempts to access any part of the Service hereby irrevocably submits to the aforesaid jurisdiction and waives any and all objections they may have to such jurisdiction on the grounds of inconvenient forum or otherwise.</p>
					<h6><b>18. Notice</b></h6>
						<p>18.1. Customer agrees that Supplier may provide notice to Customer by posting it on the Service or by sending it to the email address Customer has associated with their User Account. All notices to Supplier must be sent to the email address (or postal address) specified in the first section of this Agreement under the term "Supplier".</p>
					<h6><b>19. Miscellaneous</b></h6>
						<p>19.1. Having sufficiently considered each term of the Agreement both individually and in conjunction with other terms, each Party hereby confirms to the other that it finds the Agreement fair and not oppressive or harmful in any respect.</p>
				</div>		    

<?php include('footer.inc'); ?>				    
